name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Copy env
        run: cp .env.example .env

      - name: Generate Key
        run: php artisan key:generate

      - name: Run Tests
        run: php artisan test

  deploy:
    needs: laravel-tests
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/projeto
            git pull origin main
            docker compose down
            docker compose up -d --build
            docker exec laravel_app composer install --no-dev --optimize-autoloader
            docker exec laravel_app php artisan migrate --force
            docker exec laravel_app php artisan optimize